### ISSUE TITLE
Highlight error in line

### ISSUE THREAD

**Issue by fregante** [maxgalbu/SublimeLinter-contrib-twiglint#2]
Thanks for this package! It works correctly on my ST3b3126 on OSX 10.11 with twig-lint v1.0.1, but it doesn't highlight the column:

![screen shot 2016-10-20 at 00 01 39](https://cloud.githubusercontent.com/assets/1402241/19529009/12d74510-95e3-11e6-9c21-eda3f58d8b2a.png)

Is there some setting I'm missing or was this not implemented?

**Comment by maxgalbu** [comment]
twig-lint doesn't provide the column in the output, sorry.

Example:

```
KO in /Users/macgalbu/Downloads/file.twig (line 3)
   1      {% include "ciao.html" %}
   2
>> 3      {% casdas }
>> Unexpected "}".
```

**Comment by fregante** [comment]
Could it be implemented by looking for the _unexpected_ char on that line? If there are multiple occurrences the highlight could be yellow

**Comment by maxgalbu** [comment]
Errors can be very different, see these ones:

> Unexpected token "name" of value "xxx" ("end of statement block" expected).
> Unexpected end of template.
> Unclosed "block".

Also, from what I'm seeing in the docs, I can't get the response of the linter from the code, I just set a regexp.

**Comment by maxgalbu** [comment]
It would be different if twig-lint returned something like "the error is near this string" (near param in sublimelinter) or something, probably the closest is "Unexpected token "name" of value "xxx"" but I would need to put all the similar errors in a single regexp
