### ISSUE TITLE
Twig linting doesn't fires in Sublime / Windows

### ISSUE THREAD

**Issue by sveggiani** [maxgalbu/SublimeLinter-contrib-twiglint#3]
Hi, I cannot get the linter to work on my Windows 10 instalation.

Everything seems to be fine (see screenshots) but for some reason SublimeLinter doesn't execute the linter on my .twig files.

![image](https://user-images.githubusercontent.com/560791/29732508-443d1c8a-89bf-11e7-9c3b-49bb671db585.png)

It works flawlessy from the CLI:

![image](https://user-images.githubusercontent.com/560791/29732572-8a43ca08-89bf-11e7-8070-1c5c5e37504f.png)

Any idea?

**Comment by maxgalbu** [comment]
Should be fixed with this commit: https://github.com/maxgalbu/SublimeLinter-contrib-twiglint/commit/f5f77eedda3dc68c686796257bb53ddde82c6a78

You can try to update the plugin, I've already released a tag and it's been published on packagecontrol.io . Please let me know if it works.

**Comment by sveggiani** [comment]
@maxgalbu it's working great! thanks you!
