### ISSUE TITLE
twiglint fails to load with these errors

### ISSUE THREAD

**Issue by omikron** [maxgalbu/SublimeLinter-contrib-twiglint#5]
twiglint: Defining 'cls.syntax' has no effect anymore. Use http://www.sublimelinter.com/en/stable/linter_settings.html#selector instead.
twiglint: Defining 'cls.version_args' has no effect. Please cleanup and remove this setting.
twiglint: Defining 'cls.version_re' has no effect. Please cleanup and remove this setting.
twiglint: Defining 'cls.version_requirement' has no effect. Please cleanup and remove this setting.
twiglint disabled. 'cls.defaults' is mandatory and MUST be a dict.

**Comment by maxgalbu** [comment]
should be fixed, I'll release a version soon

**Comment by kitsguru** [comment]
any timeline on this fix?

**Comment by colinkiama** [comment]
2021 update: Any timeline on the fix?

**Comment by T-Fletcher** [comment]
June 2021 - any timeline?

**Comment by Alderi-Tokori** [comment]
July 2021... Hello?

**Comment by maxgalbu** [comment]
ok I'll get to it... sorry, I don't use Twig so often :)

**Comment by Alderi-Tokori** [comment]
Haha no worries, I managed to make do without it in the meantime :) (seeing you post reassures me, I thought we had lost you to Covid :/)

**Comment by maxgalbu** [comment]
Nope, apart from my Twig usage, I also am a father now so, my energy is elsewhere 😄 

Out of curiosity, how did you manage to solve this?

**Comment by Alderi-Tokori** [comment]
I didn't, sadly. I wrote a basic validation script that I ran against my files before pushing my code, but it's not an ideal solution by a long shot.

**Comment by maxgalbu** [comment]
Fixed and pushed tag 1.1.0

Unfortunately SublimeLinter is not very clear on what needs to be done to update a package, let's wait and see if pushing a tag is enough
